POST http://localhost:8080/user/login
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

###

POST http://localhost:8080/user/register
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

###
GET http://localhost:8080/
Content-Type: application/json
Set-Cookie: Tokend=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyTmFtZSI6ImFkbWluIiwiZXhwIjoxNjczNDI0NTY4fQ.Fu7tJdviUT_jQH87rTtHB8atmP_anysInTSfCHJlres; Path=/; Domain=localhost; Max-Age=3600; HttpOnly

{
    "username": "admin",
    "password": "admin"
}

###
GET     http://localhost:8080/game/get 
Content-Type: application/json
###
GET     http://localhost:8080/game/get/1
Content-Type: application/json
###
POST http://localhost:8080/game/create
Content-Type: application/json

{
    "Type":0, 
    "RunningTime": 30, 
    "Level":1 
}

###

POST http://localhost:8080/game/end
Content-Type: application/json

{
    "id": 4,
    "tlog":[
        {
            "Problem":"1+1",
            "Answer":2,
            "User_Answer":2,
            "Time": 10,
            "Ok": true
        },
        {
            "Problem":"1+1",
            "Answer":2,
            "User_Answer":2,
            "Time": 10,
            "Ok": true
        },
        {
            "Problem":"1+1",
            "Answer":2,
            "User_Answer":3,
            "Time": 20,
            "Ok": false
        },
        {
            "Problem":"1+1",
            "Answer":2,
            "User_Answer":3,
            "Time": 20,
            "Ok": true
        },
        {
            "Problem":"1+1",
            "Answer":2,
            "User_Answer":2,
            "Time": 10,
            "Ok": true
        },
        {
            "Problem":"1+2",
            "Answer":3,
            "User_Answer":3,
            "Time": 10,
            "Ok": true
        }
    ]
}
###
GET http://localhost:8080/rank/